In [3]:
import requests
from bs4 import BeautifulSoup

# URL of the Wikipedia page
url = "https://en.wikipedia.org/wiki/India"

# Send a request to the webpage
response = requests.get(url)

# Parse the content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Extract the main content of the article
content = soup.find_all('p')

# Combine all paragraphs into one string
paragraph = ""
for lines in content:
    paragraph += lines.text

# Print the extracted text
print(paragraph)


India, officially the Republic of India (ISO: Bhārat Gaṇarājya),[21] is a country in South Asia.  It is the seventh-largest country by area, the most populous country as of June 2023,[22][23] and from the time of its independence in 1947, the world's most populous democracy.[24][25][26] Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[j] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar, and Indonesia.
Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[27][28][29]
Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human genetic diversity.[30] Settled life

In [4]:
import requests
from bs4 import BeautifulSoup
import nltk
from nltk.tokenize import sent_tokenize

# Download the NLTK sentence tokenizer
# nltk.download()
nltk.download('punkt')

# URL of the Wikipedia page
url = "https://en.wikipedia.org/wiki/India"

# Send a request to the webpage
response = requests.get(url)

# Parse the content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Extract the main content of the article
content = soup.find_all('p')

# Combine all paragraphs into one string
paragraph = ""
for lines in content:
    paragraph += lines.text

# Tokenize the text into sentences
sentences = sent_tokenize(paragraph)
print('paragraph', paragraph)
print('sentences', sentences)

# Print the first 5 sentences as an example
for sentence in sentences[:5]:
    print(sentence)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


paragraph 
India, officially the Republic of India (ISO: Bhārat Gaṇarājya),[21] is a country in South Asia.  It is the seventh-largest country by area, the most populous country as of June 2023,[22][23] and from the time of its independence in 1947, the world's most populous democracy.[24][25][26] Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[j] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar, and Indonesia.
Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[27][28][29]
Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human genetic diversity.[30] Se

In [5]:
words = nltk.word_tokenize(paragraph)
print(words)

['India', ',', 'officially', 'the', 'Republic', 'of', 'India', '(', 'ISO', ':', 'Bhārat', 'Gaṇarājya', ')', ',', '[', '21', ']', 'is', 'a', 'country', 'in', 'South', 'Asia', '.', 'It', 'is', 'the', 'seventh-largest', 'country', 'by', 'area', ',', 'the', 'most', 'populous', 'country', 'as', 'of', 'June', '2023', ',', '[', '22', ']', '[', '23', ']', 'and', 'from', 'the', 'time', 'of', 'its', 'independence', 'in', '1947', ',', 'the', 'world', "'s", 'most', 'populous', 'democracy', '.', '[', '24', ']', '[', '25', ']', '[', '26', ']', 'Bounded', 'by', 'the', 'Indian', 'Ocean', 'on', 'the', 'south', ',', 'the', 'Arabian', 'Sea', 'on', 'the', 'southwest', ',', 'and', 'the', 'Bay', 'of', 'Bengal', 'on', 'the', 'southeast', ',', 'it', 'shares', 'land', 'borders', 'with', 'Pakistan', 'to', 'the', 'west', ';', '[', 'j', ']', 'China', ',', 'Nepal', ',', 'and', 'Bhutan', 'to', 'the', 'north', ';', 'and', 'Bangladesh', 'and', 'Myanmar', 'to', 'the', 'east', '.', 'In', 'the', 'Indian', 'Ocean', ',', 

### Stemming

In [6]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [7]:
stemmer = PorterStemmer()
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [9]:
sentences_stem = sent_tokenize(paragraph)
for i in range(len(sentences_stem)):
    words = nltk.word_tokenize(sentences_stem[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences_stem[i] = ' '.join(words)

In [10]:
print(sentences_stem)

['india , offici republ india ( iso : bhārat gaṇarājya ) , [ 21 ] countri south asia .', "it seventh-largest countri area , popul countri june 2023 , [ 22 ] [ 23 ] time independ 1947 , world 's popul democraci .", '[ 24 ] [ 25 ] [ 26 ] bound indian ocean south , arabian sea southwest , bay bengal southeast , share land border pakistan west ; [ j ] china , nepal , bhutan north ; bangladesh myanmar east .', 'in indian ocean , india vicin sri lanka maldiv ; andaman nicobar island share maritim border thailand , myanmar , indonesia .', 'modern human arriv indian subcontin africa later 55,000 year ago .', '[ 27 ] [ 28 ] [ 29 ] their long occup , initi vari form isol hunter-gather , made region highli divers , second africa human genet divers .', '[ 30 ] settl life emerg subcontin western margin indu river basin 9,000 year ago , evolv gradual indu valley civilis third millennium bce .', '[ 31 ] by 1200 bce , archaic form sanskrit , indo-european languag , diffus india northwest .', '[ 32 ] [

### Lemmatization

In [11]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [12]:
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
sentences_lemma = sent_tokenize(paragraph)
for i in range(len(sentences_lemma)):
    words = nltk.word_tokenize(sentences_lemma[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences_lemma[i] = ' '.join(words)

In [14]:
print(sentences_lemma)

['India , officially Republic India ( ISO : Bhārat Gaṇarājya ) , [ 21 ] country South Asia .', "It seventh-largest country area , populous country June 2023 , [ 22 ] [ 23 ] time independence 1947 , world 's populous democracy .", '[ 24 ] [ 25 ] [ 26 ] Bounded Indian Ocean south , Arabian Sea southwest , Bay Bengal southeast , share land border Pakistan west ; [ j ] China , Nepal , Bhutan north ; Bangladesh Myanmar east .', 'In Indian Ocean , India vicinity Sri Lanka Maldives ; Andaman Nicobar Islands share maritime border Thailand , Myanmar , Indonesia .', 'Modern human arrived Indian subcontinent Africa later 55,000 year ago .', '[ 27 ] [ 28 ] [ 29 ] Their long occupation , initially varying form isolation hunter-gatherer , made region highly diverse , second Africa human genetic diversity .', '[ 30 ] Settled life emerged subcontinent western margin Indus river basin 9,000 year ago , evolving gradually Indus Valley Civilisation third millennium BCE .', '[ 31 ] By 1200 BCE , archaic fo

### Bag of Words

In [15]:
# Library for regular expression
import re

In [16]:
sentences_bow = sent_tokenize(paragraph)

In [17]:
corpus = []

for i in range(len(sentences_bow)):
    review = re.sub('[^a-zA-Z]', ' ', sentences_bow[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
print(corpus)

['india officially republic india iso bh rat ga ar jya country south asia', 'seventh largest country area populous country june time independence world populous democracy', 'bounded indian ocean south arabian sea southwest bay bengal southeast share land border pakistan west j china nepal bhutan north bangladesh myanmar east', 'indian ocean india vicinity sri lanka maldives andaman nicobar island share maritime border thailand myanmar indonesia', 'modern human arrived indian subcontinent africa later year ago', 'long occupation initially varying form isolation hunter gatherer made region highly diverse second africa human genetic diversity', 'settled life emerged subcontinent western margin indus river basin year ago evolving gradually indus valley civilisation third millennium bce', 'bce archaic form sanskrit indo european language diffused india northwest', 'evidence today found hymn rigveda', 'preserved oral tradition resolutely vigilant rigveda record dawning hinduism india', 'drav

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [21]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### TF-IDF

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tf = TfidfVectorizer()
t = tf.fit_transform(corpus).toarray()

In [24]:
print(t)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
print(sentences_lemma)
print(corpus)

['India , officially Republic India ( ISO : Bhārat Gaṇarājya ) , [ 21 ] country South Asia .', "It seventh-largest country area , populous country June 2023 , [ 22 ] [ 23 ] time independence 1947 , world 's populous democracy .", '[ 24 ] [ 25 ] [ 26 ] Bounded Indian Ocean south , Arabian Sea southwest , Bay Bengal southeast , share land border Pakistan west ; [ j ] China , Nepal , Bhutan north ; Bangladesh Myanmar east .', 'In Indian Ocean , India vicinity Sri Lanka Maldives ; Andaman Nicobar Islands share maritime border Thailand , Myanmar , Indonesia .', 'Modern human arrived Indian subcontinent Africa later 55,000 year ago .', '[ 27 ] [ 28 ] [ 29 ] Their long occupation , initially varying form isolation hunter-gatherer , made region highly diverse , second Africa human genetic diversity .', '[ 30 ] Settled life emerged subcontinent western margin Indus river basin 9,000 year ago , evolving gradually Indus Valley Civilisation third millennium BCE .', '[ 31 ] By 1200 BCE , archaic fo

### Word2Vec

In [26]:
from gensim.models import Word2Vec

In [34]:
text = re.sub(r'\[[0-9]*\]', ' ', paragraph)
text = re.sub(r'\s+', ' ', text)
text = text.lower()
text = re.sub(r'\d', ' ', text)
text = re.sub(r'\s+', ' ', text)

In [40]:
sentences_w2v = nltk.sent_tokenize(text)
sentences_w2v = [nltk.word_tokenize(sentence) for sentence in sentences_w2v]

In [41]:
print(sentences_w2v)

[['india', ',', 'officially', 'the', 'republic', 'of', 'india', '(', 'iso', ':', 'bhārat', 'gaṇarājya', ')', ',', 'is', 'a', 'country', 'in', 'south', 'asia', '.'], ['it', 'is', 'the', 'seventh-largest', 'country', 'by', 'area', ',', 'the', 'most', 'populous', 'country', 'as', 'of', 'june', ',', 'and', 'from', 'the', 'time', 'of', 'its', 'independence', 'in', ',', 'the', 'world', "'s", 'most', 'populous', 'democracy', '.'], ['bounded', 'by', 'the', 'indian', 'ocean', 'on', 'the', 'south', ',', 'the', 'arabian', 'sea', 'on', 'the', 'southwest', ',', 'and', 'the', 'bay', 'of', 'bengal', 'on', 'the', 'southeast', ',', 'it', 'shares', 'land', 'borders', 'with', 'pakistan', 'to', 'the', 'west', ';', '[', 'j', ']', 'china', ',', 'nepal', ',', 'and', 'bhutan', 'to', 'the', 'north', ';', 'and', 'bangladesh', 'and', 'myanmar', 'to', 'the', 'east', '.'], ['in', 'the', 'indian', 'ocean', ',', 'india', 'is', 'in', 'the', 'vicinity', 'of', 'sri', 'lanka', 'and', 'the', 'maldives', ';', 'its', 'anda

In [42]:
for i in range(len(sentences_w2v)):
    sentences_w2v[i] = [word for word in sentences_w2v[i] if word not in stopwords.words('english')]

In [43]:
model = Word2Vec(sentences_w2v, min_count=1)

In [46]:
# For version less than 4.0.0
# words = model.wv.vocab 
words = set(model.wv.key_to_index.keys())

In [49]:
print(words)

{'contributes', 'substantially', 'akbar', 'advances', 'nuclear', 'hindu', 'royalty', 'neither', 'rates', 'greenhouse', 'national', 'remittances', 'marma', 'without', 'folding', 'chota', 'risks', 'tulsīdās', 'kameez', 'vastu', 'unwanted', 'war', 'co-operation', 'genres', 'services', 'deaths', 'vajpayee', 'adverse', 'far', 'largest', 'temperate', 'know-how', 'poems', 'seats', 'returned', 'population', 'drain', 'newly', 'israel', 'voted', 'countering', 'genetic', 'mayan', 'waist-line', 'defines', 'criticism', 'super', 'traders', 'grasslands', 'formations', 'premier', 'additional', 'precise', 'shoulder—serving', 'earlier', 'embodies', 'technological', 'mixing—for', 'vegetarian', 'long-lasting', 'slowly', 'active', 'marathi', 'schools', 'jackets', 'reorganisation', 'carrion', 'pakistan', 'projections', 'lentils—or', 'feudal', 'simultaneously', 'dosa', 'software', 'shoulder', 'median', 'turned', 'p.', 'endemism', 'enduring', 'intelligence', 'first', 'midday', 'serve', 'cause', 'hindu-majorit

In [50]:
vector = model.wv['far']

In [53]:
print(vector)

[-3.83629487e-03  1.60689617e-03  4.64405911e-03  1.03564681e-02
 -8.92537180e-03 -1.37321465e-02 -2.24656658e-03  1.58978719e-02
 -3.92316957e-04 -3.08731827e-03 -7.91747682e-03 -9.95930098e-03
 -6.74646394e-03 -1.14355527e-03  5.58236381e-03 -1.31945582e-02
 -5.70202991e-03 -2.28207256e-03  3.06681171e-03 -7.04887975e-03
  1.32647306e-02  2.09457125e-03 -4.19867132e-03 -3.49836191e-03
  4.22792183e-03  5.50690340e-03 -4.64226911e-03 -7.28208572e-03
 -1.18132839e-02  2.26111640e-03  7.31480774e-03  2.15780316e-03
  7.10163917e-03 -2.07598065e-03 -5.11914259e-03  1.70933345e-05
 -7.59939197e-03 -1.43374864e-03 -2.25604442e-03 -1.17538096e-02
  2.00880482e-03 -4.42394707e-03 -9.74052120e-03 -5.23976237e-03
  1.19023286e-02  2.09212326e-03 -1.11400513e-02  1.51028752e-03
 -5.83669695e-04  1.45552764e-02  7.80001283e-03  5.90133900e-03
 -9.05578118e-03  1.48857129e-04 -3.98800243e-03 -1.13068183e-03
  7.27986591e-03 -1.30965622e-04  2.67137773e-03 -6.65777270e-03
  5.24594402e-03 -7.09737

In [56]:
similar = model.wv.most_similar('far')

In [55]:
print(similar)

[('system', 0.5575825572013855), ('$', 0.556128203868866), ('growth', 0.5418418049812317), (':', 0.5373238325119019), ('c.', 0.5339769124984741), ('period', 0.5323272347450256), ('states', 0.531694233417511), ('hinduism', 0.5287865996360779), ('hindu', 0.5262055397033691), (',', 0.5256454348564148)]


### Glove

### FastText

In [59]:
from gensim.models import FastText

# Sample sentences
sentences = [["I", "love", "machine", "learning"],
             ["NLP", "is", "interesting"],
             ["Python", "is", "awesome"]]

# Train FastText model
model = FastText(sentences, min_count=1)

# Get word vector for a word
vector = model.wv['machine']
print(vector)

[ 3.77021817e-04 -6.30814233e-04  1.53462309e-03 -3.06492380e-04
 -1.30069826e-03 -2.56773760e-03 -8.10855941e-04 -8.62339279e-04
 -4.17639472e-04 -6.73011993e-04  1.79872254e-03 -7.68332829e-05
  3.64310981e-05  1.54619594e-03  2.25039927e-04 -4.94630542e-04
 -9.94413393e-04  1.24902709e-03  1.50898937e-03  5.18481131e-04
 -1.06733036e-03  4.91553161e-04 -3.40197876e-04  3.64406529e-04
 -1.20522385e-03  1.73937166e-04  2.22837832e-03 -1.22176646e-03
 -7.68651371e-04  1.49634655e-03  5.67465439e-04  1.01944222e-03
  6.99574884e-04  6.15319703e-04 -3.46618734e-04  1.83436123e-03
 -6.67900837e-04  9.98235540e-04 -2.77860701e-04 -5.28927078e-04
  1.26880116e-03 -6.30560680e-05  6.88518863e-04 -2.21783225e-03
 -1.79425508e-04 -9.06184141e-04 -1.28290814e-03 -1.73092543e-04
 -1.62863533e-03 -8.45089817e-05  5.96138067e-04  2.50154058e-03
  1.12917961e-03  1.66597951e-04 -2.51446501e-03 -1.53431552e-03
  3.33444099e-04 -1.23327354e-03 -8.78580729e-04 -5.46658353e-04
  6.20551640e-04 -4.33632